### ISSUE TITLE
X

### ISSUE THREAD

**Issue by poornan** [poornan/reference-implementation#1]
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>jms-ejb</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>ejb</packaging>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <failOnMissingWebXml>false</failOnMissingWebXml> </properties>

    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>8.0</version> <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ejb-plugin</artifactId>
                <version>3.2.1</version>
                <configuration>
                    <ejbVersion>3.2</ejbVersion> </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```

**Comment by poornan** [comment]
```
package com.example.jms;

import javax.annotation.Resource;
import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.jms.*;

@Stateless
public class MessageProducerBean {

    @Resource(lookup = "jms/myDistributedQueue") // Replace with your JNDI name
    private Queue distributedQueue;

    @Inject
    private JMSContext context;

    public void sendMessage(String messageText) {
        try {
            TextMessage message = context.createTextMessage(messageText);
            TemporaryQueue tempQueue = context.createTemporaryQueue();
            message.setJMSReplyTo(tempQueue);  // Set the ReplyTo destination

            // Create a consumer *on the temporary queue* within the producer
            // to receive the reply.  This is synchronous.
            try (JMSConsumer consumer = context.createConsumer(tempQueue)) {
                context.createProducer().send(distributedQueue, message);
                System.out.println("Producer: Sent message: " + messageText);

                // Synchronously wait for the reply.  Set a timeout!
                TextMessage replyMessage = (TextMessage) consumer.receive(10000); // 10-second timeout
                if (replyMessage != null) {
                    System.out.println("Producer: Received reply: " + replyMessage.getText());
                } else {
                    System.out.println("Producer: No reply received within timeout.");
                }
            }

        } catch (JMSException e) {
            throw new RuntimeException("Error sending/receiving JMS message", e);
        }
    }
}

```

**Comment by poornan** [comment]
```
package com.example.jms;

import javax.annotation.Resource;
import javax.ejb.ActivationConfigProperty;
import javax.ejb.MessageDriven;
import javax.ejb.MessageDrivenContext;
import javax.jms.*;

@MessageDriven(activationConfig = {
        @ActivationConfigProperty(propertyName = "destinationLookup", propertyValue = "jms/myDistributedQueue"),
        @ActivationConfigProperty(propertyName = "destinationType", propertyValue = "javax.jms.Queue")
})
public class MessageConsumerBean implements MessageListener {

    @Resource
    private MessageDrivenContext mdc; //for rollback

    @Override
    public void onMessage(Message message) {
        try {
            if (message instanceof TextMessage) {
                TextMessage textMessage = (TextMessage) message;
                System.out.println("Consumer (MDB): Received message: " + textMessage.getText());

                // Get the JMSReplyTo destination.
                Destination replyTo = message.getJMSReplyTo();
                if (replyTo != null) {

                    //create producer for the reply
                    JMSContext context = mdc.lookup("java:/comp/DefaultJMSConnectionFactory").
                            asInstanceOf[ConnectionFactory].createContext(); // get ConnectionFactory
                    JMSProducer replyProducer = context.createProducer();

                    TextMessage replyMessage = context.createTextMessage("Reply to: " + textMessage.getText());
                    replyProducer.send(replyTo, replyMessage); // Send the reply.
                    System.out.println("Consumer (MDB): Sent reply.");
                } else {
                    System.out.println("Consumer (MDB): No JMSReplyTo destination specified.");
                }
            } else {
                System.out.println("Consumer (MDB): Received message of unexpected type: " + message.getClass().getName());
            }
        } catch (JMSException e) {
            System.err.println("Consumer (MDB): Error processing message: " + e.getMessage());
           mdc.setRollbackOnly(); // IMPORTANT: Rollback if there's an exception
        }
    }
}


```

**Comment by poornan** [comment]
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>jms-client</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.oracle.weblogic</groupId>
            <artifactId>wlthint3client</artifactId>
            <version>14.1.1.0</version>  </dependency>
         <dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<version>8.0</version> <scope>provided</scope>
		</dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.example.jms.Client</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
             <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.example.jms.Client</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>


```

**Comment by poornan** [comment]
```
package com.example.jms;
import javax.jms.*;
import javax.naming.Context;
import javax.naming.InitialContext;
import java.util.Hashtable;

public class Client {
	public static void main(String[] args) throws Exception {

		Hashtable<String, String> env = new Hashtable<>();
		env.put(Context.INITIAL_CONTEXT_FACTORY, "weblogic.jndi.WLInitialContextFactory");
		env.put(Context.PROVIDER_URL, "t3://localhost:7001"); // Replace with your WebLogic URL

		Context ctx = new InitialContext(env);

		ConnectionFactory connectionFactory = (ConnectionFactory) ctx.lookup("java:/comp/DefaultJMSConnectionFactory"); // Default CF
		Queue queue = (Queue) ctx.lookup("jms/myDistributedQueue"); // Lookup the *distributed* queue

		try (JMSContext context = connectionFactory.createContext()) {
			// (1) Send Message and Wait for Reply (Producer Role)

			// Create a temporary queue for the reply
			TemporaryQueue tempQueue = context.createTemporaryQueue();

			// Create a message and set JMSReplyTo
			TextMessage message = context.createTextMessage("Hello from Client!");
			message.setJMSReplyTo(tempQueue);

			// Create a producer and send the message
			JMSProducer producer = context.createProducer();
			producer.send(queue, message);
			System.out.println("Client: Sent message: " + message.getText());

			// Create a consumer on the temporary queue to receive the reply.
			try (JMSConsumer consumer = context.createConsumer(tempQueue)) {
				// Synchronously wait for reply.
				TextMessage replyMessage = (TextMessage) consumer.receive(10000); // Timeout!
				if (replyMessage != null) {
					System.out.println("Client: Received reply: " + replyMessage.getText());
				} else {
					System.out.println("Client: No reply received within timeout.");
				}
			}
		}
	}
}

```

**Comment by poornan** [comment]
```
topology:
  Name: JmsDomain # Change domain name here if you want.

  # JMS Server
  JMSServer:
    'MyJMSServer':  # Name of the JMS Server
      Target: 'AdminServer'  # Target to a server or cluster
      PersistentStore: !find:FileStore,name=MyFileStore  # Using a default file store - you might want a JDBC store

  # File Store
  FileStore:
      'MyFileStore':
        Directory: ./filestores/MyFileStore #default, override in update section if you want
        Target: 'AdminServer' #must be the same that the JMSServer

  # JMS System Module
  JMSSystemResource:
    'MyJMSModule':
      Target: 'AdminServer'  # Target to a server or cluster
      SubDeployment:
        'MySubDeployment':
          Target: 'MyJMSServer'  # Target the subdeployment to the JMS Server
      JmsResource:
        # Connection Factory
        ConnectionFactory:
          'MyConnectionFactory':
            JNDIName: 'jms/myConnectionFactory' #custom CF
            SubDeploymentName: 'MySubDeployment'

        # Distributed Queue
        UniformDistributedQueue:
          'MyDistributedQueue':
            JNDIName: 'jms/myDistributedQueue'
            SubDeploymentName: 'MySubDeployment' # Crucial for distributed queues!

resources:
    AppDeployment:
        'jms-ejb':
            SourcePath: 'wlsdeploy/applications/jms-ejb-1.0-SNAPSHOT.jar' # Relative to the archive or absolute path
            Target: 'AdminServer'  # Or your cluster name
            ModuleType: 'ejb'


```

**Comment by poornan** [comment]
```
#jms-variables.properties
FileStore.MyFileStore.Directory=/path/to/your/filestores/MyFileStore

```

**Comment by poornan** [comment]
```
# Using zip (from the root of your jms-ejb project)
zip -r archive.zip target/jms-ejb-1.0-SNAPSHOT.jar
mv archive.zip /path/to/where/you/run/wdt/wlsdeploy # put the zip next to your model.yaml

# OR, using jar (from the root of your jms-ejb project):
jar -cvf archive.jar target/jms-ejb-1.0-SNAPSHOT.jar
mv archive.jar /path/to/where/you/run/wdt/wlsdeploy # put the zip next to your model.yaml

```

**Comment by poornan** [comment]
```
$WL_HOME/weblogic-deploy/bin/createDomain.sh \
    -oracle_home $ORACLE_HOME \
    -domain_home /path/to/your/domain \
    -model_file jms-model.yaml \
    -archive_file archive.zip  \
    -domain_type WLS   \
    -variable_file jms-variables.properties

```

**Comment by poornan** [comment]
```
$WL_HOME/weblogic-deploy/bin/updateDomain.sh \
    -oracle_home $ORACLE_HOME \
    -domain_home /path/to/your/domain \
    -model_file jms-model.yaml \
    -archive_file archive.zip \
    -variable_file jms-variables.properties

```

**Comment by poornan** [comment]
```
<project ...>  ...
    <properties>
        <wdt.home>/path/to/your/wdt/installation</wdt.home> <oracle.home>/path/to/your/oracle/home</oracle.home> <domain.home>/path/to/your/domain/home</domain.home>  <domain.type>WLS</domain.type> <wdt.model.file>${project.basedir}/src/main/wlsdeploy/model/jms-model.yaml</wdt.model.file>
		<wdt.variable.file>${project.basedir}/src/main/wlsdeploy/properties/jms-variables.properties</wdt.variable.file>
		<wdt.archive.file>${project.build.directory}/wlsdeploy/archive.zip</wdt.archive.file>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ejb-plugin</artifactId>
                <version>3.2.1</version>
                <configuration>
                    <ejbVersion>3.2</ejbVersion>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>copy-wdt-resources</id>
                        <phase>prepare-package</phase>  <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/wlsdeploy</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/src/main/wlsdeploy</directory>
                                    <filtering>true</filtering> </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>create-wdt-archive</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/assembly.xml</descriptor> </descriptors>
                            <finalName>archive</finalName> <appendAssemblyId>false</appendAssemblyId>  <outputDirectory>${project.build.directory}/wlsdeploy</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

             <plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<id>update-weblogic-domain</id>
						<phase>install</phase> <goals>
							<goal>exec</goal>
						</goals>
						<configuration>
							<executable>${wdt.home}/bin/updateDomain.sh</executable>
							<arguments>
								<argument>-oracle_home</argument>
								<argument>${oracle.home}</argument>
								<argument>-domain_home</argument>
								<argument>${domain.home}</argument>
								<argument>-model_file</argument>
								<argument>${wdt.model.file}</argument>
								<argument>-archive_file</argument>
								<argument>${wdt.archive.file}</argument>
                                <argument>-domain_type</argument>
                                <argument>${domain.type}</argument>
                                <argument>-variable_file</argument>
                                <argument>${wdt.variable.file}</argument>
							</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>

        </plugins>
    </build>
</project>

```

**Comment by poornan** [comment]
```
<assembly xmlns="http://maven.apache.org/ASSEMBLY/2.1.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/ASSEMBLY/2.1.0 http://maven.apache.org/xsd/assembly-2.1.0.xsd">
    <id>wdt-archive</id>
    <formats>
        <format>zip</format> </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <fileSets>
        <fileSet>
            <directory>${project.build.directory}</directory>
            <outputDirectory>wlsdeploy/applications</outputDirectory> <includes>
                <include>${project.build.finalName}.jar</include>
            </includes>
        </fileSet>
    </fileSets>
</assembly>

```

**Comment by poornan** [comment]
```
topology:
  Name: JmsDomain

  JMSServer:
    'MyJMSServer':
      Target: 'AdminServer'
      PersistentStore: !find:FileStore,name=MyFileStore

  FileStore:
    'MyFileStore':
      Directory: '${FileStore.MyFileStore.Directory}' # Use the property
      Target: 'AdminServer'

  JMSSystemResource:
    'MyJMSModule':
      Target: 'AdminServer'
      SubDeployment:
        'MySubDeployment':
          Target: 'MyJMSServer'
      JmsResource:
        ConnectionFactory:
          'MyConnectionFactory':
            JNDIName: 'jms/myConnectionFactory'
            SubDeploymentName: 'MySubDeployment'
        UniformDistributedQueue:
          'MyDistributedQueue':
            JNDIName: 'jms/myDistributedQueue'
            SubDeploymentName: 'MySubDeployment'

resources:
    AppDeployment:
        'jms-ejb':
            SourcePath: 'wlsdeploy/applications/${project.build.finalName}.jar'  # Use Maven property
            Target: 'AdminServer'
            ModuleType: 'ejb'

```
